from vector_store import add_example

examples = [
    ("🇺🇸 +1888 • 🇦🇺 +61 #WTS DID & SIP Trunk — Ready Now @Activepaidviop", "BAN"),
    ("Giving away my 15-inch MacBook Air (M4) — barely used and still in excellent condition. DM me.", "BAN"),
    ("📢 Students! Need Academic Help? Get expert help in Assignments, Homework, Online classes. Fast • Reliable • Affordable 👉 TutorSolve", "BAN"),
    ("Hi all! I lost my v!rg!n!ty at Valour House today... If anyone has seen it please let me know!", "BAN"),
    ("QX Automatic Mahjong Table – giving away brand new, comes complete with tiles. If interested DM me.", "BAN"),
    ("給她發Pm，以獲得很酷的服務，非常合法的弓工作和性愛", "BAN"),
    ("@Yrsgsuregirl", "BAN"),
    ("Hey guys I'm looking for a developer to join me on the VIP program comfortable in coding blockchain and AI ML. Deadline is in a few hours.", "SAFE"),
    ("Hi, im looking for a black wallet at either LT38, around icube or the bus stop. If found please pm me thank you.", "SAFE"),
    ("Check out this open source project: https://github.com/0mgABear/susmessagebot", "SAFE"),
    ("https://github.com/0mgABear/susmessagebot", "SAFE"),
    ("Looking for 1–3 people for remote earnings . Everything can be done from your phone. Income — €1,500 per week. Message 👉 @realewan", "BAN"),
    ('i can send it if u want?', "SAFE"),
    ("We are looking for reliable partners for long-term collaboration!\nNo risks or shady deals!\nEarn between $1400 and 1600$ per week\nConsistent income—can also be done remotely!\n\nIf you're interested, contact @Anna_Lour", "BAN")
    ('i can send that message too and see if my bot bans me haha', "SAFE"),
    ("I am offering you a wide range of services like finding valid business emails and targeted b2b LinkedIn lead generation by sales navigator. I am excellent at providing clean, bounce-free, Geo-targeted leads based on your targeted market.\n\n\n\nI am an expert in:\n\n\n\nB2B Lead Generation\nLinkedin Lead Generation\nB2B targeted emails\nValid Emails\nData Collection and Research\nWeb research\nWeb Scrapping\nData Entry\nCoinbase leads\nSweepstakes leads\nGambler leads\nForex leads\nCrypto leads\nTrading leads\nB2c leads\nLead generation \n\n\nMy tools and resources:\n\nLinkedin sales navigator\nE-mail Finder & Verification Tools \nGoogle Advanced Search \nZoominfo, Yellow Page, Crunchbase, AngelList, Yelp\nCompany Website, and so on.\n\n\nHere's what I need from you:\n\nTargeted Industries\nTargeted Locations\nTargeted contact titles\nTargeted employee size(if needed)\n\n\nWhy you should appoint me.!\n\n\n\nFast response\n100% accuracy\nReplacement for invalid leads\n24/7 support\n\nDrop message \n@Creative_Lead_MWC\n@rpaexpert\nhttps://wa.me/+923710042488", "BAN"),
    ('Australia 🇦🇺 | Canada 🇨🇦 | UK | Denmark 🇩🇰 | 🇬🇧USA 🇺🇸 + Toll Free and Local Number is available\n\n𝗦𝗜𝗣 𝗧𝗿𝘂𝗻𝗸𝘀 & 𝗗𝗜𝗗𝘀 – 𝗥𝗲𝗮𝗱𝘆\n 𝗜𝗻𝘀𝘁𝗮𝗻𝘁 𝗔𝗰𝘁𝗶𝘃𝗮𝘁𝗶𝗼𝗻 𝗼𝗻 𝗩𝗲𝗿𝗶𝗳𝗶𝗲𝗱 𝗥𝗼𝘂𝘁𝗲𝘀 \n\nUp to 20 channels \n🛎️ message me now to get yours\n@Cloudcallvoip', "BAN"),
    ('info. @ra_Cyt', "BAN"),
    ('Quickie @ra_Cyt', "BAN"),
    ('@slimsgGirl', "BAN"),
    ('She’s allowed? @ra_Cyt', "BAN"),
    ('noooo not my thing, if anyones giving away free openai credits, then send them my way :D /j', "SAFE"),
    ('yesss let it be reinforced :DD', "SAFE"),
    ('ikik', "SAFE"),
    ('issok', "SAFE"),
    ('It’s all credits', "SAFE"),
    ('oh WHAT', "SAFE"),
    ('as i was ssaying', "SAFE"),
    ('they say 99%', "SAFE"),
    ('Fr', "SAFE"),
    ('Sjksfngasf', "SAFE"),
    ('ah ykw', "SAFE"),
    ('FRRRR (this is gonna get banned ngl)', "SAFE"),
    ("iut's open sourcce gais", "SAFE"),
    ('Ah icic', "SAFE"),
    ('oh but 50 requests a day :<', "SAFE"),
    ('Chop chop chop wrk 5.9k pm free job fast job', "BAN"),
    ('Urgent wrk paynow 1.9k , check my story if you do pm', "BAN"),
    ('how is the human trafficking from sg to jb now', "SAFE"),
    ('Heyyy\n☺️☺️', "BAN"),
    ('woodlands any vep check?', "SAFE"),
    ('any new abt jb to sg? @Rac_yy', "BAN"),
    ('@qzvxlp', "BAN"),
    ('Fast hop 9.9k pm', "BAN"),
    ('hi has anyone seen a navy blue Polo Ralph Lauren hoodie in as6-04-21? i lost it there saturday. if anyone has seen it please dm me @chenkeia. Thankss!', "SAFE"),
    ('I’m looking for two people\n\n• No need to go to an office\n• No need to use a computer\n• Fully flexible schedule\n• From day one: €315 per week\n\nRequirements:\n✅ Age between 18 and 65\n✅ No previous experience required\n\nInterested?\nSend me a private message with “+” 👉 @ashhley_1', "BAN"),
    ('Chop chop chop wrk 5.9k pm free job fast job', "BAN"),
    ('Pm me 9.9k', "BAN"),
    ('🗺️ Tired of guessing Singapore rents?\n\nWe built a free community rent map where real tenants pin what they actually pay — HDB rooms, condos, landed, all areas.\n\n✅ 100% free\n✅ No sign-up needed\n✅ Pin your rent in 30 seconds\n✅ See real rents near any MRT or neighbourhood\n\nHelp your fellow Singaporeans make smarter rental decisions, please pin your rent👇\n\nsingaporerent dot sg', "BAN"),
    ('Job Opportunities \n2 Task;\nPm to make 1100SGD\nQuick and fast deal\nSecond Task:\nNumber for otp also\nEarn $300\nInterested heads only', "BAN"),
    ('Chop chop chop wrk 5.9k pm free job fast job', "BAN"),
    ('Pm now if int in 9.9k', "BAN"),
    ('🔥 𝙉𝙊 𝙉𝙊𝙄𝙎𝙀. 𝙅𝙐𝙎𝙏 𝙍𝙀𝙎𝙐𝙇𝙏𝙎 🔥\n\n𝙏𝙞𝙧𝙚𝙙 𝙤𝙛 𝙗𝙖𝙙 𝙑𝙤𝙄𝙋 𝙧𝙤𝙪𝙩𝙚𝙨 & 𝙪𝙣𝙨𝙩𝙖𝙗𝙡𝙚 𝙎𝙄𝙋?\n𝙎𝙩𝙤𝙥 𝙡𝙤𝙨𝙞𝙣𝙜 𝙘𝙖𝙡𝙡𝙨. 𝙁𝙞𝙭 𝙞𝙩 𝙩𝙤𝙙𝙖𝙮 ⚡️\n\n🌐 𝙎𝙄𝙋 𝙏𝙧𝙪𝙣𝙠 (𝙄𝙣𝙗𝙤𝙪𝙣𝙙/𝙊𝙪𝙩𝙗𝙤𝙪𝙣𝙙)\n\n📡 𝘽𝙪𝙡𝙠 𝙎𝙈𝙎 (𝙒𝙤𝙧𝙡𝙙𝙬𝙞𝙙𝙚)\n\n📞 𝘿𝙄𝘿 𝙉𝙪𝙢𝙗𝙚𝙧𝙨 (𝙐𝙎𝘼/𝙐𝙆/𝘾𝘼 + 𝙢𝙤𝙧𝙚)\n\n👑 𝙄𝙑𝙍 & 𝘾𝙖𝙡𝙡 𝘾𝙚𝙣𝙩𝙚𝙧 𝙎𝙚𝙩𝙪𝙥\n\n\n⚡️ 𝙎𝙩𝙖𝙗𝙡𝙚 | 𝙁𝙖𝙨𝙩 | 𝙍𝙚𝙡𝙞𝙖𝙗𝙡𝙚\n\n📩 𝘿𝙈 @𝙨𝙥𝙤𝙤𝙛𝙞𝙣𝙜_𝙘𝙖𝙡𝙡𝙚𝙧02', "BAN"),
    ('Sgjbcheckpointgroup', "SAFE"),
    ('@xllyzx1', "BAN"),
    ('bus to sg go? @sicklegurl', "BAN"),
    ('Check her page @mikay835', "BAN"),
    ('I’m looking for two people\n\n• No need to go to an office\n• No need to use a computer\n• Fully flexible schedule\n• From day one: €350 per week\n\nRequirements:\n✅ Age between 18 and 65\n✅ No previous experience required\n\nInterested?\nSend me a private message with “+” 👉 @ashhley_1', "BAN"),
    ('offer available  chck my story !!! \nPm if also want', "BAN"),
    ('I’m available for cybersecurity and blackhat work.\nWebsite attacks, website creation & cloning, database extraction, all-country databases, and Office leads.', "BAN"),
    ('Busses still? @sgpeear', "BAN"),
    ('Fast job 1.2 pm now', "BAN"),
    ('I’m looking for some motivated people.\n\nWhat I offer:\n• 100% online earnings.\n• All you need is a smartphone.\n• Average actual earnings: ~€315 per week.\n\nSpots are very limited - there are only a few left.\n\nWant to know what this is all about?\n→ Just send a private message with “+” to 👉 @ashhley_1', "BAN"),
    ('Looking for unusual content? 🔥\nJust come in here and those who have already joined will not regret it 😉\nCheck the link in bio now before you miss it', "BAN"),
    ('Anyone used the KTM bot recently? Have an issue with my ticket purchase and WhatsApp-ed the support number/called since 3 days ago and no replies. Even tried emailing the email address they provided support@theticketbot.com but it says this email is non existent.', "SAFE"),
    ('Check her page @neesaxo', "BAN"),
    ('hello darling , on srvice massage 🫧🫧', "BAN"),
    ('People needed fast Job 7.9k check story if can\n\n @Juel19  urgent pm', "BAN"),
    ('how’s sg to jb? @BB_pear', "BAN"),
    ('https://www.tiktok.com/@trustedhandymansg?_r=1&_t=ZS-95uIA5M7Hmf', "BAN"),
    ('that’s ago @URsicklegurl', "BAN"),
    ('Anyone interested in 9.9k pm dm \nFree work \nGood work', "BAN"),
    ('offer available   Urgent work Payout 2.7k check story   @juh024 Pm if also want !!!!', "BAN"),
    ('OBTAIN YOUR FULL DRIVING LICENCE\n\n DRIVING LICENCE DVLA APPROVED \n\nFULL LICENSE ✅💯\nPROVISIONAL✅ 💯\nBAN UPLIFTING✅ 💯\nDVLA APPROVED ✅💯', "BAN"),
    ('Tell me the tool to bypass OTP', "BAN"),
    ('Tap sg to jb ! @xy_pea', "BAN"),
    ('Any update on the SG > JB immigration now? Any human traffic queue ?', "SAFE"),
    ('@xllyzx1\n\n\n\n\n\n@xllyzx1', "BAN"),
    ('@GroupHelpBot hi my friend @WarrenWonder got banned after asking hows the queue like today, possible to get him unbanned?', "SAFE"),
    ('https://www.causewaylink.com.my/cw2-runs-24-hours-starting-from-august-1-2022/ theres 24hours cw bus', "SAFE"),
    ('tap @xy_pea', "BAN"),
    ('I’m looking for some motivated people.\n\nWhat I offer:\n• 100% online earnings.\n• All you need is a smartphone.\n• Average actual earnings: ~€350 per week.\n\nSpots are very limited - there are only a few left.\n\nWant to know what this is all about?\n→ Just send a private message with “+” to 👉 @ashhley_1', "BAN"),
    ('For Jb to sg @URserii', "BAN"),
    ('🔠🅰️😊😚,  😊🔡🍓🔠 🤩🔤🤩\n\n🇺🇸 𝐔𝐒𝐀 𝐓𝐨𝐥𝐥-𝐅𝐫𝐞𝐞 𝐍𝐮𝐦𝐛𝐞𝐫𝐬 𝐀𝐯𝐚𝐢𝐥𝐚𝐛𝐥𝐞 (𝟖𝟎𝟎 / 𝟖𝟖𝟖 / 𝟖𝟕𝟕 / 𝟖𝟔𝟔)\n\n  🚀 𝐏𝐫𝐨𝐟𝐞𝐬𝐬𝐢𝐨𝐧𝐚𝐥 & 𝐑𝐞𝐥𝐢𝐚𝐛𝐥𝐞 𝐂𝐚𝐥𝐥𝐢𝐧𝐠 𝐟𝐨𝐫 𝐁𝐮𝐬𝐢𝐧𝐞𝐬𝐬𝐞𝐬\n\n🔥 🇺🇸 𝗨𝗦𝗔 | 🇦🇺 𝗔𝘂𝘀𝘁𝗿𝗮𝗹𝗶𝗮 | 🇬🇧 𝗨𝗞\n🇨🇦 𝗖𝗮𝗻𝗮𝗱𝗮 | 🇳🇱 𝗡𝗲𝘁𝗵𝗲𝗿𝗹𝗮𝗻𝗱𝘀 | 🇵🇱 𝗣𝗼𝗹𝗮𝗻𝗱 | SPAIN🇪🇸\n🇵🇹 𝗣𝗼𝗿𝘁𝘂𝗴𝗮𝗹 | 🇨🇭 𝗦𝘄𝗶𝘁𝘇𝗲𝗿𝗹𝗮𝗻𝗱 | 🇧🇪 𝗕𝗲𝗹𝗴𝗶𝘂𝗺\xa0 🇭🇰 Hong Kong \n\n ✅ 𝐈𝐧𝐛𝐨𝐮𝐧𝐝 & 𝐎𝐮𝐭𝐛𝐨𝐮𝐧𝐝 𝐂𝐚𝐥𝐥𝐢𝐧𝐠\n ✅ 𝐂𝐚𝐥𝐥 𝐂𝐞𝐧𝐭𝐞𝐫 & 𝐓𝐞𝐥𝐞𝐦𝐚𝐫𝐤𝐞𝐭𝐢𝐧𝐠 𝐑𝐞𝐚𝐝\n ✅ 𝐈𝐕𝐑, 𝐒𝐈𝐏 𝐓𝐫𝐮𝐧𝐤 \n ✅ 3CX Configuration \n ✅ 𝐂𝐥𝐞𝐚𝐧 𝐑𝐨𝐮𝐭𝐞𝐬 • 𝐇𝐢𝐠𝐡 𝐀𝐧𝐬𝐰𝐞𝐫 𝐑𝐚𝐭𝐞  \n\n \n📌All PROVIDERS AVAILABLE SUCH AS \n\n👍 TWILIO\n👍 TELNYX \n👍 DIDLOGIC \n👍 VONAGE \n👍 PBX\n👍 SIGNALWIRE\n👍 MESSAGEBIRD AND MORE\n\n 📩 Message me 👇👇\n✅ @proconnect_sip\n✅ @proconnect_sip\nJoin channel @proconnect_hub for more', "BAN"),
    ('Ungrat wrk payout 2.3k look my story can do dm @muj031', "BAN"),
    ('For sg to jb? @URserii', "BAN"),
    ('https://mothership.sg/2026/05/jb-checkpoint-crack-down-bus-illegal/?fbclid=IwdGRzaARmfdJjbGNrBGZ9y2V4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHmZt7Mjj3Pv7d9oSk1xh1LB895DSgZSiPhBVrr5Qypi5egcZ34-R1-8XZvhK_aem_TSfNBv-X8aLav7DOzxItuw&sfnsn=mo', "SAFE"),
    ('Hello 👋🏻 everyone I have a legitimate and reliable crypto platform that offers 5%-10% ROI daily of your investment, you can withdraw at any time. And they are really paying their investors here on telegram. Message me privately for more information if it interests you!', "BAN"),
    ('Name sg to jb ? @URserii', "BAN"),
    ('Looking for pple who want good job payout now 1.8k dm', "BAN"),
    ('for? @serixily', "BAN"),
    ('Hows to queue from JB to SG?', "SAFE"),
    ('☄️ 𝐃𝐈𝐃 𝐍𝐮𝐦𝐛𝐞𝐫𝐬 & 𝐒𝐈𝐏 𝐓𝐫𝐮𝐧𝐤𝐬\n\n🌐 𝐆𝐥𝐨𝐛𝐚𝐥 𝐂𝐨𝐯𝐞𝐫𝐚𝐠𝐞: 🇺🇸 USA +1 (800 / 888)\n\n🇬🇧 UK +44\n🇨🇦 Canada +1\n🇦🇺 Austr\nalia +61\n🇳🇱 Netherlands +31\n🇵🇱 Poland +48\n🇨🇭 Switzerland +41\n\n⚡️ Instant Activation\n\n📞 Inbound & Outbound Calling\n\n⭐️ Up to 20 Channels\n\n✔️ Fully Compatible with 3CX\n\n✔️ Reliable • Secure • High-Quality Routes\n\n💬 DM Now: @NexvoDial👩\u200d🚀', "BAN"),
    ('Good morning Jb to sg ? @serixily', "BAN"),
    ('I will tell ICA officer u said this and they’ll pat u down', "SAFE"),
    ("Hi! Not sure if this is allowed, if not allowed pls let me know I'll delete\n\nWill anyone be going KSL next few days? Could I trouble you to help me buy contacts from a store at ground floor? Will pay u first, thank you", "SAFE"),
    ('🌞🌞🌞🌞🌞🌞🌞🌞\n\nGood morning 🌞🌞🌞🌞 \n\n\nP m \nNow \n\xa0\xa0 Fxxst\n\xa0\xa0\xa0 In \n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Come \n\n@Zhixaunpui🌞🌞\n🌞🌞🌞🌞🌞🌞🌞', "BAN"),
    ('15+ @basexz', "BAN"),
    ('anyone can paynow me tng ewallet balance', "BAN"),
    ('good job payout now 2.5k pm if also want !!', "BAN"),
    ('@pxly_ling', "BAN"),
    ('Have a nice trip to Cambodia. Want to bring more USD cash? You can some at airport. Rates are low. And bring back if rgere are left over', "BAN"),
    ('open for? @Xp_seRi', "BAN"),
    ('Check my story pm if also want fast cash payout', "BAN"),
    ('Urgent fast Job 2.9k check story if can\n\n @Juel15  urgent pm', "BAN"),
    ('https://gofund.me/27b9a5b1b', "BAN"),
    ('Kranji jb? @UREMRY', "SAFE"),
    ('Kranji spa? @UREMRY', "BAN"),
    ('Oh!! Thank you.\nThat young couple told me just scan credit card lolol. Heng i hv cash!!!', "BAN"),
    ('Ungent work pm me 9.9k', "BAN"),
    ('How to q from jb to sg now?', "BAN"),
    ('@seen_Xp_seRi', "BAN"),
    ('Sg>jb', "SAFE"),
    ('Anyone need bj in sg ?', "BAN"),
    ('@QX_XLLY\n\n\n\n\n\n        @QX_XLLY', "BAN"),
    ('check story pm if also want !!', "BAN"),
    ('Anyone free @Aurixxty', "BAN"),
    ('^ spam', "SAFE"),
    ('@Niswanatalia', "BAN"),
    ('Hi. How’s the bus que to Sg?', "SAFE"),
    ("Hi, may I know how's sg to jb ?", "SAFE"),
    ('Sg to jb', "SAFE"),
    ('Pm 2.7 now if int', "BAN"),
    ('Wrk urgent fast Job 2.9k check story if can\n\n urgent pm', "BAN"),
    ('@qui_ling\n\n\n\n\n\n\n@qui_ling', "BAN"),
    ('Giv ing away my 15-inch MacBook Air (M4) — bareIy used and stiII in exceIIent condition.', "BAN"),
    ('ig curiosity gets reward jb to sg @localjesLyn', "BAN"),
    ('admin pls do not delete text, I’ve got a report from Yishun \n        @localjesLyn', "BAN"),
    ('how is jb-> sg now?', "SAFE"),
    ('Sg to jb queue how!', "SAFE"),
    ('💔 𝐋𝐈𝐒𝐓 𝐆𝐑𝐎𝐔𝐏 💔\n\n    ❣️𝐓𝐞𝐫𝐛𝐚𝐫𝐮 𝐛𝐞𝐬𝐭❣️\n▁▂▃▄❀✿♛✿❀▄▃▂▁\n❤️\u200d🔥 𝐉𝐎𝐈3𝐍 𝐆𝐑〇𝐔𝐏 ❤️\u200d🔥\n    ❣️𝐓𝐄𝐋𝐄𝐆𝐑𝐀𝐌❣️\n\n💔Vip Budak Kecik❤️\u200d🔥\n💔Vip Budak Skolah❤️\u200d🔥\n💔Vip Budak Pedo❤️\u200d🔥\n💔Vip Budak Rogol❤️\u200d🔥\n💔Vip Budak Underg❤️\u200d🔥\n💔Vip Budak Sexs❤️\u200d🔥\n💔Vip Mom And Son❤️\u200d🔥\n💔Vip Full Melayu❤️\u200d🔥\n💔Vip Full Indo Viral❤️\u200d🔥\n💔Vip Tudung Melayu❤️\u200d🔥\n💔Vip Hijab Melayu❤️\u200d🔥\n💔Vip Mlayu Campur❤️\u200d🔥\n💔Vip India Vs Malay❤️\u200d🔥\n💔Vip Malaysia Viral❤️\u200d🔥\n💔Vip Remaja18+❤️\u200d🔥\n💔Vip Wanita Hamil❤️\u200d🔥\n💔Vip New Colmek❤️\u200d🔥\n💔Vip Skodeng❤️\u200d🔥\n💔Vip Chinese 18+❤️\u200d🔥\n💔Vip Lesbian Hots❤️\u200d🔥\n💔Vip New Blue❤️\u200d🔥\n💔Vip Stw Para Istri❤️\u200d🔥\n💔Vip Face crot❤️\u200d🔥\n💔Vip Ratu Goyang❤️\u200d🔥\n💔Vip Promote Bbw❤️\u200d🔥\n💔Vip Ruang Imjinasi❤️\u200d🔥\n💔Vip Play Boy Form❤️\u200d🔥\n💔Vip Tim 5 Jari Gp❤️\u200d🔥\n💔Vip Vitub Group❤️\u200d🔥\n\n𝑆𝐸𝑀𝑈𝐴  𝐺𝑅𝑂𝑈𝑃 𝐼𝑁𝐼\n𝐴𝐾𝐴𝑁 𝑆𝐸𝑇𝐴𝑌 𝑇𝐸𝑅𝑈𝑆\n𝐷𝐼𝑈𝑃𝐷𝐴𝑇𝐸 𝐷𝐴𝑅𝐼\n𝑆𝐸𝑀𝐴𝑆𝐴 𝐾𝐸 𝑆𝐸𝑀𝐴𝑆𝐴\n𝑆𝐴𝐻𝐴𝐽𝐴 𝐽𝑂𝐼𝑁\n\n  𝑁𝐴𝐾 𝐽𝑂𝐼𝑁 𝑃𝑅𝑂𝑀𝑂\n   𝐵𝑂𝐿𝐸𝐻 𝑃𝑀 𝑆𝐿𝑅\n@Babyqila_123com\nTrusted Seller 💯💯\n💔💔💔💔💔💔💔💔💔\n❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥❤️\u200d🔥\n❣️❣️❣️❣️❣️❣️❣️❣️❣️', "BAN"),
    ('@ynk_ping', "BAN"),
    ('@soojz1\n\n\n@soojz1', "BAN"),
    ('scam^', "SAFE"),
    ('11:48a.m SG custom human line no q', "SAFE"),
    ('DISCOUNT ::::::: @Real_prinses', "BAN"),
    ('admin ban this', "SAFE"),
    ('@Meriol2', "BAN"),
    ('@ping1Ling\n\n\n\n\n\n\n\n\n\n\n\n\n@ping1Ling', "BAN"),
    ('@ping1Ling\n\n\n\n\n\n\n\n@ping1Ling', "BAN"),
    ('suggesttt sg to jb.. @xp_llin', "BAN"),
    ('Suggesttt jb to sg .. @xp_llin', "BAN"),
    ('SG NSFW LGBT SPA private social group. Were all here to enjoy good vibes and share info + stories (no drama, no racism). this is a space for everyone within our community who loves a little adventure 💦 spread 🫂 not hate\n\nChannel / Groups 👇👇👇\n\nhttps://sgbodymassages-n.t-spaa.com/group\n\nAll members here can now join this. 🇲🇾🇸🇬 🇨🇳', "BAN"),
    ('sugggestted? Jb stay sg. @xp_lin', "BAN"),
    ('@ping1Ling\n\n\n\n\n\n\n@ping1Ling', "BAN"),
    ('@x_i_n_y_i\n\n\n\n\n\n\n@x_i_n_y_i', "BAN"),
    ('Only singaporean ! I have a simple task for S$200\nNo age preference \nPm', "BAN"),
    ('Hi everyone,\n\nGi ving away 2 × 3 sixty 16 inch foIdabIe bicycIes (chameIeon bIue & red) – both in good working condition.\n\nGreat for commuting or casuaI rides.\n\nIf you’re inter ested, feeI free to D M.\n\nThanks.', "BAN"),
    ('Anyone int in 5.7k pm me', "BAN"),
    ('Wan 2.2k fast job fst payout  pm if also want !', "BAN"),
    ('@rooob3r \n\nPlease reach at 8.30 am to take bus service number as 950 in Woodlands Temporary Bus Interchange if possible.', "BAN"),
    ('@Xp_Linn Jb to sg now…', "BAN"),
    ('@Lee_Xin_Yi\n\n\n\n\n\n@Lee_Xin_Yi', "BAN"),
]


if __name__ == "__main__":
    for message, label in examples:
        add_example(message, label)
        print(f"Added [{label}]: {message[:50]}...")
    print(f"\nDone! {len(examples)} examples added to ChromaDB.")
